// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-6Htqmvo4oojGXz7dwb3_ep817z5kTfY',
    appId: '1:512883715209:web:a0e85f2f14d3777a782a58',
    messagingSenderId: '512883715209',
    projectId: 'crud-firebase-flutter-6eef1',
    authDomain: 'crud-firebase-flutter-6eef1.firebaseapp.com',
    storageBucket: 'crud-firebase-flutter-6eef1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewaK5_eMmodydcCk7wAk-5ez1Mq_k-NU',
    appId: '1:512883715209:android:3451b112cec71dd5782a58',
    messagingSenderId: '512883715209',
    projectId: 'crud-firebase-flutter-6eef1',
    storageBucket: 'crud-firebase-flutter-6eef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_V29K9owHTv1HFpDX8hqdzYEjDGWjzM0',
    appId: '1:512883715209:ios:6f407c8d3485d38c782a58',
    messagingSenderId: '512883715209',
    projectId: 'crud-firebase-flutter-6eef1',
    storageBucket: 'crud-firebase-flutter-6eef1.appspot.com',
    iosBundleId: 'com.example.cadastro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_V29K9owHTv1HFpDX8hqdzYEjDGWjzM0',
    appId: '1:512883715209:ios:6f407c8d3485d38c782a58',
    messagingSenderId: '512883715209',
    projectId: 'crud-firebase-flutter-6eef1',
    storageBucket: 'crud-firebase-flutter-6eef1.appspot.com',
    iosBundleId: 'com.example.cadastro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-6Htqmvo4oojGXz7dwb3_ep817z5kTfY',
    appId: '1:512883715209:web:5d93ce21b4e1c474782a58',
    messagingSenderId: '512883715209',
    projectId: 'crud-firebase-flutter-6eef1',
    authDomain: 'crud-firebase-flutter-6eef1.firebaseapp.com',
    storageBucket: 'crud-firebase-flutter-6eef1.appspot.com',
  );
}
